info:
    app:
        company: RizalTech
        description: Master Spring Boot
        name: Spring Boot Master Class Course
        version: 1.0.0
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
    info:
        env:
            enabled: true
server:
    port: 9080
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: hello
        url: jdbc:h2:mem:testdb-dev-environment
        username: hello
    h2:
        console:
            enabled: true
            path: /h2-dev
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    main:
        banner-mode: 'off'
